apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: classroom-assessment
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64(password)
  MYSQL_DATABASE: Y2xhc3Nyb29tX2Ri  # base64(classroom_db)
  MYSQL_USER: cm9vdA==             # base64(root)
  MYSQL_PASSWORD: cGFzc3dvcmQ=      # base64(password)
