apiVersion: v1
kind: Service
metadata:
  name: classroom-manager
  namespace: 25rp18224-nzayisenga
  labels:
    app: classroom-manager
spec:
  type: LoadBalancer
  selector:
    app: classroom-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: classroom-manager-internal
  namespace: 25rp18224-nzayisenga
  labels:
    app: classroom-manager
spec:
  type: ClusterIP
  selector:
    app: classroom-manager
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
